In [1]:
from dc4.dc4_utils import play_game_player_player
from dc4.game import Game
from dc4.agent import Agent
from dc4.move import Move

In [5]:
import numpy as np

In [7]:
arr1 = np.array([1,3,5])
arr2 = np.array([True, False, True])

print(str(arr1 * arr2))

[1 0 5]


In [9]:
print(str(arr1**2.2))

[ 1.         11.21157846 34.49324154]


In [11]:
np.sum(arr1)

9

In [14]:
print(arr1 / np.sum(arr1))

[0.11111111 0.33333333 0.55555556]
